"use strict";
//By specifying "use strict"; at the top of JS file...
//then we cannot declare variables w/o using var/let keyword !
fname="Raj"; // will throw error...
var lname="Parikshit"; // correct !